# Generated by Django 4.1.4 on 2022-12-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funCinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата выхода'),
        ),
    ]
