# Generated by Django 4.1.2 on 2022-10-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(help_text='Введите свое полное ФИО', max_length=100)),
                ('number', models.IntegerField(max_length=20, verbose_name='Идентификатор')),
            ],
        ),
        migrations.CreateModel(
            name='Salespeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100, verbose_name='Город проживания')),
            ],
        ),
    ]
